services:

# --------- Domotique ---------
  caddy:
    profiles:
      - public
    image: caddy
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      TZ: Europe/Paris

  homeassistant:
    profiles:
      - domotique
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Paris

  mqtt:
    profiles:
      - domotique
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/mosquitto-data:/mosquitto
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883

  zigbee2mqtt:
    profiles:
      - domotique
    container_name: zigbee2mqtt
    depends_on:
      - mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Paris
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/your-adapter-id:/dev/ttyACM0

# --------- Media ---------
  transmission:
    profiles:
      - media
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - .env
    environment:
      - USER=transmission
      - PASS=${TRANSMISSION_PASS}
      - PUID=${ID}
      - PGID=${GID}
      - TZ=Europe/Paris
    volumes:
      - ./transmission/data:/config
      - $HOME/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  
  jellyfin:
    profiles:
      - media
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${ID}:${GID}
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: $HOME/downloads
        target: /media
    restart: 'unless-stopped'

# --------- NAS ---------
