services:
  # swag:
  #   image: linuxserver/swag
  #   container_name: swag
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - URL=MON-NOM-DE-DOMAINE
  #     - VALIDATION=http
  #   volumes:
  #     - ${PWD}/swag/homeassistant.subdomain.conf:/config/nginx/proxy-confs/homeassistant.subdomain.conf
  #   ports:
  #     - 443:443
  #     - 80:80
  #   restart: unless-stopped
  
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/configuratio:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Paris

  mqtt:
    image: eclipse-mosquitto:2.1-alpine
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/mosquitto-config:/mosquitto/config
    ports:
      - "1883:1883"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Paris
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/your-adapter-id:/dev/ttyACM0