services:

# --------- Domotique ---------
  ddns-updater:
    profiles:
      - public
      - all
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: host
    volumes:
      - ./caddy/ddns-updater:/updater/data
    environment:
      - TZ=Europe/Paris
      - PERIOD=1h
    restart: unless-stopped

  caddy:
    profiles:
      - public
      - all
    image: caddy
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      TZ: Europe/Paris

  homeassistant:
    profiles:
      - domotique
      - public
      - all
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Paris

  mqtt:
    profiles:
      - domotique
      - all
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/mosquitto-data:/mosquitto
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883

  zigbee2mqtt:
    profiles:
      - domotique
      - all
    container_name: zigbee2mqtt
    depends_on:
      - mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Paris
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/your-adapter-id:/dev/ttyACM0

  ha-linky:
    profiles:
      - linky
      - all
    container_name: ha-linky
    restart: unless-stopped  
    image: ha-linky
    network_mode: host
    environment:
      - SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN}
      - WS_URL=ws://127.0.0.1:8123/api/websocket
      - TZ=Europe/Paris
    volumes:
      - ./ha-linky:/data

# --------- Media ---------
  transmission:
    profiles:
      - media
      - all
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - .env
    environment:
      - USER=transmission
      - PASS=${TRANSMISSION_PASS}
      - PUID=${ID}
      - PGID=${GID}
      - TZ=Europe/Paris
    volumes:
      - ./transmission/data:/config
      - $HOME/downloads:/downloads
    network_mode: host
    restart: unless-stopped
  
  jellyfin:
    profiles:
      - media
      - public
      - all
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    user: ${ID}:${GID}
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: $HOME/downloads
        target: /media
    restart: 'unless-stopped'

# --------- NAS ---------
  nextcloud:
    profiles:
      - nas
      - public
      - all
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    environment:
      - APACHE_PORT=11000
    ports:
      - "8080:8080"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer