
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  external_url: https://homeassistant.example.com
  internal_url: http://127.0.0.1:8123

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - 192.168.0.0/16

# google_assistant:
#   project_id: maison-10611
#   service_account: !include service_account.json
#   report_state: true
#   exposed_domains:
#     - light
#     - script