version: 5
mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://mqtt:1883
serial:
    port: /dev/ttyACM0
    adapter: zstack
advanced:
    channel: 11
    network_key: GENERATE
    pan_id: GENERATE
    ext_pan_id: GENERATE
frontend:
    enabled: true
homeassistant:
    enabled: true