homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
# Enable the Zigbee2MQTT frontend
frontend:
  port: 8080
advanced:
  network_key:
    - 162
    - 166
    - 39
    - 41
    - 83
    - 253
    - 230
    - 143
    - 78
    - 223
    - 34
    - 195
    - 45
    - 183
    - 11
    - 159
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00158d0007e2002f':
    friendly_name: temp Salon
  '0x00158d0003ef0aaa':
    friendly_name: porte entre
  '0x00158d0007f2a0d6':
    friendly_name: temp cuisine
  '0x00158d0003cd1f14':
    friendly_name: temp chambre
